import Footer from "@/components/footer";
import NavBar from "@/components/nav-bar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-background">
      <NavBar />
      {children}
      <Footer />
    </div>
  );
}
